import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import { disputeCashPayment, getPaymentReceipt, getWorkerCashPayments, workerConfirmCashPayment } from "../../services/paymentService";
const money = (value) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR" }).format(Number(value));

export default function CashPayments() {
  const [payments, setPayments] = useState([]), [loading, setLoading] = useState(true);
  useEffect(() => { (async () => { try { const result = await getWorkerCashPayments(); setPayments(result.data || []); } catch { toast.error("Could not load cash payments"); } finally { setLoading(false); } })(); }, []);
  const replace = (updated) => setPayments((current) => current.map((payment) => payment.id === updated.id ? updated : payment));
  const confirm = async (payment) => { if (!window.confirm(`Confirm that you received ${money(payment.amount)} in cash?`)) return; try { replace((await workerConfirmCashPayment(payment.id)).data); toast.success("Cash payment confirmed. A receipt is available to both parties."); } catch (error) { toast.error(error.response?.data?.message || "Could not confirm payment"); } };
  const dispute = async (payment) => { const disputeReason = window.prompt("Explain why you are disputing this cash payment:"); if (!disputeReason?.trim()) return; try { replace((await disputeCashPayment(payment.id, disputeReason)).data); toast.success("Payment sent to support review."); } catch (error) { toast.error(error.response?.data?.message || "Could not dispute payment"); } };
  const receipt = async (id) => { try { const { data } = await getPaymentReceipt(id); const text = `HomeConnect Cash Payment Receipt\nReceipt: ${data.receiptNumber}\nJob: ${data.job.title}\nAmount: ${money(data.amount)}\nStatus: ${data.status}`; const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([text], { type: "text/plain" })); link.download = `${data.receiptNumber}.txt`; link.click(); URL.revokeObjectURL(link.href); } catch { toast.error("Could not download receipt"); } };
  if (loading) return <div>Loading cash payments...</div>;
  return <div className="space-y-6"><div><h1 className="text-3xl font-bold">Cash payments</h1><p className="mt-1 text-gray-500">Confirm cash only after you have received the stated amount.</p></div>{payments.length ? <div className="space-y-4">{payments.map((payment) => <section key={payment.id} className="rounded-xl bg-white p-5 shadow"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-semibold">{payment.job.title}</h2><p className="text-sm text-gray-500">Customer: {payment.job.customer.fullName} · {money(payment.amount)}</p></div><span className="rounded-full bg-amber-100 px-3 py-1 text-sm">{payment.status.replaceAll("_", " ")}</span></div>{payment.status === "CASH_CUSTOMER_CONFIRMED" && <div className="mt-4 flex gap-3"><button onClick={() => confirm(payment)} className="rounded-lg bg-green-600 px-4 py-2 font-medium text-white">I received {money(payment.amount)}</button><button onClick={() => dispute(payment)} className="rounded-lg bg-red-600 px-4 py-2 font-medium text-white">Dispute payment</button></div>}{payment.status === "SUCCESS" && <div className="mt-3"><p className="text-sm text-green-700">Paid. Receipt: {payment.receiptNumber}</p><button onClick={() => receipt(payment.id)} className="mt-2 text-sm font-medium text-blue-700 underline">Download receipt</button></div>}</section>)}</div> : <div className="rounded-xl bg-white p-8 text-gray-500 shadow">No assigned cash payments.</div>}</div>;
}
