import { useEffect, useMemo, useState } from "react";
import toast from "react-hot-toast";
import { getMyJobs } from "../../services/jobService";
import { confirmCashPayment, createPayment, getPaymentReceipt, getPayments } from "../../services/paymentService";

const money = (value) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR" }).format(Number(value));
const label = (status) => status.replaceAll("_", " ");

export default function Payments() {
  const [jobs, setJobs] = useState([]), [payments, setPayments] = useState([]), [jobId, setJobId] = useState(""), [saving, setSaving] = useState(false);
  const payable = useMemo(() => jobs.filter((job) => job.status === "COMPLETED" && !payments.some((payment) => payment.jobId === job.id)), [jobs, payments]);
  useEffect(() => { (async () => { try { const [j, p] = await Promise.all([getMyJobs(), getPayments()]); setJobs(j.data || []); setPayments(p.data || []); } catch { toast.error("Could not load payments"); } })(); }, []);
  const create = async (event) => { event.preventDefault(); if (!jobId) return; setSaving(true); try { const result = await createPayment({ jobId, paymentMethod: "CASH" }); setPayments((current) => [result.data, ...current]); setJobId(""); toast.success("Cash payment created. Record handover when you pay the worker."); } catch (error) { toast.error(error.response?.data?.message || "Could not create payment"); } finally { setSaving(false); } };
  const handover = async (id, amount) => { if (!window.confirm(`Confirm that you handed ${money(amount)} to the worker?`)) return; try { const result = await confirmCashPayment(id); setPayments((current) => current.map((p) => p.id === id ? result.data : p)); toast.success("Waiting for the worker to confirm receipt."); } catch (error) { toast.error(error.response?.data?.message || "Could not record handover"); } };
  const downloadReceipt = async (id) => { try { const { data } = await getPaymentReceipt(id); const worker = data.job.applications?.[0]?.workerProfile?.user; const text = `HomeConnect Cash Payment Receipt\nReceipt: ${data.receiptNumber}\nJob: ${data.job.title} (${data.job.id})\nCustomer: ${data.job.customer.fullName}\nWorker: ${worker?.fullName || "Assigned worker"}\nAmount: ${money(data.amount)}\nCustomer confirmed: ${new Date(data.customerCashConfirmedAt).toLocaleString("en-IN")}\nWorker confirmed: ${new Date(data.workerCashConfirmedAt).toLocaleString("en-IN")}\nStatus: ${data.status}`; const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([text], { type: "text/plain" })); link.download = `${data.receiptNumber}.txt`; link.click(); URL.revokeObjectURL(link.href); } catch (error) { toast.error(error.response?.data?.message || "Could not download receipt"); } };
  return <div className="space-y-6"><div><h1 className="text-3xl font-bold">Cash payments</h1><p className="mt-1 text-gray-500">Cash is marked paid only after both you and the assigned worker confirm it.</p></div>
    <section className="rounded-xl bg-white p-5 shadow"><h2 className="text-lg font-semibold">Create cash payment</h2>{payable.length ? <form onSubmit={create} className="mt-4 flex flex-col gap-3 sm:flex-row"><select value={jobId} onChange={(e) => setJobId(e.target.value)} className="rounded-lg border p-3" required><option value="">Select a completed job</option>{payable.map((job) => <option key={job.id} value={job.id}>{job.title} — {money(job.budget)}</option>)}</select><button disabled={saving} className="rounded-lg bg-blue-600 px-5 py-3 font-medium text-white disabled:opacity-60">{saving ? "Creating..." : "Create cash payment"}</button></form> : <p className="mt-3 text-sm text-gray-500">No completed jobs are waiting for payment.</p>}</section>
    <section className="overflow-hidden rounded-xl bg-white shadow"><div className="border-b px-5 py-4 font-semibold">Payment timeline</div>{payments.length ? <div className="divide-y">{payments.map((payment) => <div key={payment.id} className="p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-semibold">{payment.job?.title}</p><p className="text-sm text-gray-500">{money(payment.amount)} · {payment.receiptNumber || "Receipt created after cash payment"}</p></div><span className="rounded-full bg-amber-100 px-3 py-1 text-sm text-amber-800">{label(payment.status)}</span></div><div className="mt-3 text-sm text-gray-600">Created → Customer handover → Worker receipt confirmation → Paid</div>{payment.status === "CASH_PENDING" && <button onClick={() => handover(payment.id, payment.amount)} className="mt-4 rounded-lg bg-green-600 px-4 py-2 font-medium text-white">I handed over {money(payment.amount)}</button>}{payment.status === "CASH_CUSTOMER_CONFIRMED" && <p className="mt-3 text-sm text-blue-700">Worker confirmation is due by {new Date(payment.workerConfirmationDeadline).toLocaleDateString("en-IN")}.</p>}{payment.status === "SUCCESS" && <div className="mt-3"><p className="text-sm text-green-700">Payment confirmed by both parties. Receipt: {payment.receiptNumber}</p><button onClick={() => downloadReceipt(payment.id)} className="mt-2 text-sm font-medium text-blue-700 underline">Download receipt</button></div>}{["CASH_DISPUTED", "CASH_REVIEW"].includes(payment.status) && <p className="mt-3 text-sm text-red-700">This payment is under support review.</p>}</div>)}</div> : <p className="p-5 text-gray-500">No payments yet.</p>}</section>
  </div>;
}
